### ISSUE TITLE
Grafana Container Not Connecting to Local Host

### ISSUE THREAD

**Issue by samueljrodriguez** [wozniakpawel/synology-grafana-prometheus-overly-comprehensive-dashboard#2]
I'm getting this error for the container.
Connecting to localhost:3000 (127.0.0.1:3000) wget: can't connect to remote host (127.0.0.1): Connection refused

I've followed the directions, but can't figure out what's going on. When I go to my IP and 3340, the page says connection refused also. I've turned off my firewall and still the same issue. 

Any chance you can help?

**Comment by samueljrodriguez** [comment]
Firewall took a while to turn off apparently. I'm able to access Grafana. I'll see if I can figure out what's going on with my firewall.

**Comment by wozniakpawel** [comment]
I’m honestly surprised you’re able to access Grafana at localhost:3000 (127.0.0.1), it’s close to impossible. That’s normally your own computer’s IP and not the NAS’. You should just use the IP you normally use to access the NAS (DSM), just change the default :5001 to :3340.
