### ISSUE TITLE
snmp-exporter restarting

### ISSUE THREAD

**Issue by mack-psu** [wozniakpawel/synology-grafana-prometheus-overly-comprehensive-dashboard#4]
After following the readme, SNMP is not starting

error msg="Error parsing config file" err="priv password is missing, required for SNMPv3 with priv"

In Synology, enabled SNMPv3, set username to exporter, MD5 protocol, set password, enabled SNMP privacy, DES, set different password.  set these two values in the snmp.yml file.

snmp-exporter constantly reboots.

**Comment by mack-psu** [comment]
Running DSM 7.2.1-69057 Update 4 (latest)
and
Container Manager 20.10.23-1437 (latest)

**Comment by wozniakpawel** [comment]
Try a different password with alphanumeric characters only, maybe there’s a problem parsing it from the config file due to some special character.

**Comment by mack-psu** [comment]
That was it.  only alpha characters used.  no numbers.  no special characters.  thanks!

**Comment by wozniakpawel** [comment]
Glad to have helped. Enjoy!
