### ISSUE TITLE
Speedtest exporter do not export ?

### ISSUE THREAD

**Issue by TheRealBix** [wozniakpawel/synology-grafana-prometheus-overly-comprehensive-dashboard#7]
Hi,

First, thanks for your guide and dashboard, both are pretty useful !

However I have an issue with speedtest data, I have none... I set 5min instead of 60 in prometheus.yml for testing purposes, but all I get is "...level=error msg="could not fetch user information: EOF" from speedtest exporter logs.

Are you familiar with this issue ?

**Comment by wozniakpawel** [comment]
I have had a couple of people reach out to me with this issue.

I am unfortunately not sure what is wrong, it still works for me and I don't have a spare system to set everything up again from scratch. I hope that someone encounters this issue, solves it, and posts a solution here.

If this continues to be a problem, I might switch to a different speedtest exporter altogether.

**Comment by TheRealBix** [comment]
I'm now using a fork of danopstech/speedtest_exporter and it's working as intended.
I don't really what and how it is fixed, but it works.
https://github.com/danopstech/speedtest_exporter/compare/main...aaronmwelborn:speedtest_exporter:main

**Comment by wozniakpawel** [comment]
Great, thank you so much for the update! I will test this for myself and if it works I will replace the exporter with this fork.

**Comment by wozniakpawel** [comment]
Hi. Could you tell me if you only replaced [this line](https://github.com/wozniakpawel/synology-grafana-prometheus-overly-comprehensive-dashboard/blob/2876ef0c8e9bcede8ceb36b6ff448bea41ea6013/master/compose.yaml#L117) in the compose file with
```image: ghcr.io/aaronmwelborn/speedtest_exporter:latest```
or did you do anything extra to make it work? I am not having luck making this fork work for me so far.

**Comment by TheRealBix** [comment]
ah indeed, here's my compose bit : 
`  speedtest:
    image: "ghcr.io/aaronmwelborn/speedtest_exporter:latest"
    container_name: speedtest_exporter
    hostname: speedtest
    ports:
      - 9877:9877
    entrypoint: ["/speedtest_exporter", "-server_id", "52534", "-server_fallback"] 
    networks:
      - prometheus_net
    security_opt:
      - no-new-privileges=true
    read_only: true
    user: xxx:xxx
    restart: unless-stopped`

**Comment by wozniakpawel** [comment]
Ah yes of course, the default port is different on that fork. Thanks for the pointer!
