### ISSUE TITLE
Container Activity Monitor is empty

### ISSUE THREAD

**Issue by xeviff** [wozniakpawel/synology-grafana-prometheus-overly-comprehensive-dashboard#9]
hello. First of all, let me recognise this as **the best monitoring dashboard I've seen for Dockers**. Also, I must say I tried a couple some years ago and afterwards I discarded all. This is the first one where I can see clearly which container is taking more CPU/RAM/IO, so my congrats, it's amazing.
Said that. I see that one panel doesn't work: `Container Activity Monitor`. It's a pity because I'm very interested in that one. Most of the others works, and I can't locate any relevant error log.
You can see the image here:
![image](https://github.com/user-attachments/assets/420078df-8fb6-4805-84ee-2f7a1e645d7f)

Any hint?

**Comment by wozniakpawel** [comment]
Odd. If you hover your mouse above the Container Activity Monitor, click the three dots in the top right corner and select "Inspect" and then "Data", what does it show?

**Comment by xeviff** [comment]
Wow, today I relaunched again the docker stack to leave here an screenshot (I only want to monitor when strange CPU loads appears f.i.) 
and surprisingly I've found this:

![image](https://github.com/user-attachments/assets/0349b4ef-8c40-403a-93b6-93adee11f9a4)

So it seems to have been fixed alone hehehe
Again, looks very nice all this. Thank you very much for this dashboard. Keep rocking!
